### ISSUE TITLE
GDscript support

### ISSUE THREAD

**Issue by JekSun97** [Joy-less/Embers#1]
Excellent plugin, I use the same one only for Lua.
will there be gdscript support?

**Comment by Joy-less** [comment]
Thank you, however this repository is not designed to provide GDScript functionality due to the work involved. Someone else is free to try with this repository. But I recommend using Godot C# and using Ruby where needed.

**Comment by Joy-less** [comment]
Reopening this issue because this is now possible with Embers 3.

See the example in the `README`:
```cs
public partial class CounterScript : Node {
    [Export] RichTextLabel CounterLabel;

    Scope Scope;

    public override void _Ready() {
        Scope = new Scope();
        Scope.Axis.Object.SetInstanceVariable("@counter_label", CounterLabel);
        Scope.Evaluate(@"
@counter = 0
def _process
  @counter += 1
  @counter_label.text = @counter.to_s
end
        ");
    }
    public override void _Process(double Delta) {
        Scope.Axis.Main.CallMethod("_process");
    }
}
```

Note that it uses C# as a middleman and it's recommended to write performance intensive code in C# or GDScript.
